name: Deploy Yin & Yang

on:   # on defines triggers so push to main will trigger this workflow
  push:
    branches: [ "main" ] # Only trigger if pushing to main

jobs: # A group of related actions. There can be multiple jobs - e.g. build, test, deploy. They will run in parallel if possible
  deploy: # Job name
    runs-on: ubuntu-latest  # Tell github to spin up a ubuntu VM to use to run this job

    steps: # Run job steps in sequence and if any fail, the whole job fails
      - name: Checkout code # Just a label for the process step
        uses: actions/checkout@v4 # Call library code to pull the repo code into the runner (the vm). Use v4 of the lib code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Add these into github secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Yin # path to Dockerfile is relative to the project dir not the workflow dir
        run: |
          docker build -t oldgitdocker/yin:latest ./yin 
          docker push oldgitdocker/yin:latest

      - name: Build and push Yang
        run: |
          docker build -t oldgitdocker/yang:latest ./yang
          docker push oldgitdocker/yang:latest

      - name: Copy compose.yaml to VM
        uses: appleboy/scp-action@v0.1.7  # Effectively scp to copy files to remote machine. Appleboy is the username for the creator
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "compose.yaml"          # Use a comma list for more files
          target: "/home/${{ secrets.VM_USER }}/"

      - name: Restart remote containers  # Effectively ssh to login to the vm
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}    # Need sudo for docker as the group permissions are not yet set
          script: |
            cd /home/${{ secrets.VM_USER }} 
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d
